dic = {
    "FILE_RENAME": _("名前を変更"),
    "FILE_CHANGEATTRIBUTE": _("属性を変更"),
    "FILE_MAKESHORTCUT": _("ショートカットを作成"),
    "FILE_TRASH": _("ゴミ箱へ移動"),
    "FILE_DELETE": _("完全削除"),
    "FILE_VIEW_DETAIL": _("詳細情報を表示"),
    "FILE_SHOWPROPERTIES": _("プロパティを表示"),
    "FILE_MKDIR": _("新規ディレクトリ作成"),
    "FILE_FILEOPTEST": _("テスト中のファイルオペレーションを実行"),
    "FILE_EXIT": _("終了"),

    "EDIT_COPY": _("コピー"),
    "EDIT_CUT": _("切り取り"),
    "EDIT_PAST": _("貼り付け"),
    "EDIT_NAMECOPY": _("名前をコピー"),
    "EDIT_FULLPATHCOPY": _("フルパスをコピー"),
    "EDIT_SELECTALL": _("全て選択"),
    "EDIT_SEARCH": _("検索"),
    "EDIT_UPDATEFILELIST": _("最新の情報に更新"),
    "EDIT_MARKITEM": _("チェック／チェック解除"),
    "EDIT_MARKITEM_ALL": _("すべてチェック"),
    "EDIT_UNMARKITEM_ALL": _("すべてチェック解除"),
    "EDIT_MARKITEM_INVERSE": _("チェック状態反転"),
    "EDIT_OPENCONTEXTMENU": _("コンテキストメニューを開く"),

    "MOVE_FORWARD": _("開く"),
    "MOVE_FORWARD_ADMIN": _("管理者として開く"),
    "MOVE_EXEC_ORIGINAL_ASSOCIATION": _("独自関連付けで実行"),
    "MOVE_FORWARD_TAB": _("別のタブで開く"),
    "MOVE_FORWARD_STREAM": _("開く(ストリーム)"),
    "MOVE_BACKWARD": _("上の階層へ"),
    "MOVE_NEWTAB": _("新しいタブ"),
    "MOVE_CLOSECURRENTTAB": _("現在のタブを閉じる"),
    "MOVE_TOPFILE": _("先頭ファイルへ"),
    "MOVE_SPECIAL_UP": _("上にジャンプ"),
    "MOVE_SPECIAL_DOWN": _("下にジャンプ"),
    "MOVE_HIST_NEXT": _("次の履歴位置へ"),
    "MOVE_HIST_PREV": _("前の履歴位置へ"),
    "MOVE_MARKSET": _("表示中の場所をマーク"),
    "MOVE_MARK": _("マークした場所へ移動"),
    "MOVE_INPUT_DIR": _("パスを指定して移動"),

    "MOVE_ADD_FAVORITE": _("現在の場所をお気に入りに登録"),
    "MOVE_SETTING_FAVORITE": _("お気に入りディレクトリの設定"),
    "MOVE_SETTING_OPEN_HERE": _("ここで開く コマンドの設定"),

    "READ_PREVIEW": _("プレビュー"),
    "READ_CONTENT_PREVIEW": _("ファイルをプレビュー"),
    "READ_CONTENT_READHEADER": _("テキストヘッダー読み"),
    "READ_CONTENT_READFOOTER": _("テキストフッター読み"),

    "READ_CURRENTFOLDER": _("現在のフォルダ名を読み上げ"),
    "READ_LISTITEMNUMBER": _("リスト項目数を読み上げ"),
    "READ_LISTINFO": _("一覧情報を読み上げ"),
    "READ_SETMOVEMENTREAD": _("移動先の読み方を設定"),

    "TOOL_DIRCALC": _("フォルダ容量計算"),
    "TOOL_HASHCALC": _("ファイルハッシュの計算"),
    "TOOL_EXEC_PROGRAM": _("ファイル名を指定して実行"),
    "TOOL_ADDPATH": _("環境変数PATHに追加"),
    "TOOL_EJECT_DRIVE": _("ドライブの取り外し"),
    "TOOL_EJECT_DEVICE": _("デバイスの取り外し"),

    "VIEW_SORTNEXT": _("次の並び順"),
    "VIEW_SORTSELECT": _("並び順を選択"),
    "VIEW_SORTCYCLEAD": _("昇順/降順切り替え"),
    "VIEW_DRIVE_INFO": _("ドライブ情報の表示"),
    "VIEW_SORT_COLUMN": _("カラムの並び替え"),

    "ENV_REGIST_ORIGINAL_ASSOCIATION": _("独自関連付けの管理"),
    "ENV_KEY_CONFIG": _("キーボードショートカットの設定"),
    "ENV_TESTDIALOG": _("テストダイアログを表示"),
    "ENV_PASTTABTEST": _("貼り付け状況ダイアログテスト"),
    "ENV_FONTTEST": _("フォントテストダイアログを表示"),

    "HELP_VERINFO": _("バージョン情報"),

    "": ""  # セパレータ追加時用
}
